### PR TITLE
Aper decoder fixes

### PR DESCRIPTION
**Pull request by KrzysztofW**
Hi

I've been using your asn1c fork with APER support for a while and fixed some issues related mostly to the decoder. Could you have a look on the patches?
BR

### CODE REVIEW

**Comment by AuthenticEshkinKot** [comment]
Hi, @KrzysztofW !
I've tried to build your branch, but it crashed with error "asn1p_integer.h: no such file".

**Comment by KrzysztofW** [comment]
Hi
Yes two files were missing due to manual cherry-picking. I just fixed that.
BTW, I think the last patch "fix alignment of octet strings of length < 3 bytes" is not complete. It should only apply to not fixed length octet strings. I have impression that the nokalva's playground always adds padding for octet strings regardless of their lengths which confuses me.

**Comment by KrzysztofW** [comment]
Hi @AuthenticEshkinKot 
I re-uploaded the last patch after re-reading the X691 specs. My fix only applies to fixed-length strings. This was the only missing thing to correctly decode short (< 3 bytes) variable length octet strings. With this patch asn1c behaves exactly the same as the Nokalva playground for both variable and fixed length bit strings and octet strings, regardless of their size (> 2 or <= 2 bytes).
BR

**Comment by AuthenticEshkinKot** [comment]
It seem to be OK now. Thanks for your PR!

**Comment by KrzysztofW** [comment]
Hi, thank you. Do you think the aper support will be merged one day on vlm? Why is it taking so long?
BR

**Comment by AuthenticEshkinKot** [comment]
I think that APER support is rather complicated feature and it should be tested thoroughly before pulling in, but vlm has no time for that.

**Pull request merged**
